- name: Preparing ec2
  hosts: all
  become: true
  gather_facts: false

  roles:
    - role: common
      tags: always
    - role: selinux
      tags: selinux
    - role: docker
      tags: docker
      when: inventory_hostname in groups["Control_Plane"] + groups["Workers"]
    - role: kubernetes
      tags: kubernetes
      when: inventory_hostname in groups["Control_Plane"] + groups["Workers"]
    - role: Jenkins
      tags: jenkins
      when: inventory_hostname in groups["Jenkins"]
    - role: Kube_sa
      tags: kube_sa
      when: inventory_hostname in groups["Control_Plane"]
      become: no