- name: Preparing ec2
  hosts: all
  become: true
  gather_facts: false

  roles:
    - role: common
      tags: always
    - role: selinux
      tags: selinux
    - role: docker
      tags: docker
    - role: kubernetes
      tags: kubernetes
